### ISSUE TITLE
Archivos del Alhambra Switch corruptos

### ISSUE THREAD

**Issue by altenife** [PCBPrints/Alhambra-switch#1]
Buenos días, iba a descargarme el archivo del alhambra switch para freecad, pero no me permite abrirlo, me lanza el siguiente error.

`Traceback (most recent call last) file "" line 1 in: invalid proyect file (D:/ruta del archivo): ios_base::failbit set:iostream stream error`

Es Step también me lanza error:
`Traceback (most recent call last) file "" line 1 in canot read STEP file.`

El STL me lanza el siguiente error.
No se pudo abrir el archivo, codigo de error: 0X80004005

Estoy utilizando windows 10 y la version 0.18 de Freecad.

**Comment by javacasm** [comment]
Los dos archivos son correctos. Quizás no lo descargaste bien.
